name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull from hub, merge, and push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure Git with a user name and email
          git config --global user.email "ayanavasarka@gmail.com"
          git config --global user.name "ayaisthebest"
          
          # Add the Hugging Face remote
          git remote add hub https://ayaisthebest:$HF_TOKEN@huggingface.co/spaces/ayaisthebest/InterviewAssistant
          
          # Pull the latest changes from the hub using a rebase strategy
          git pull hub main
          
          # Push the merged changes back to the hub
          git push hub main
